language: python
sudo: required
dist: xenial
python: "3.7"

install:
  - pip install pipenv
  - nvm install 8.11.1
  - nvm list
  - npm install -g serverless
  - npm install

script:
  # deploy service to lambda
  - ls -R
  - sls deploy